name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: use node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm ci
      run: npm config set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_TOKEN }}' && npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm test
