name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: "12.13.0"
    - name: npm ci
      run: npm config set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_TOKEN }}' && npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm test
